### ISSUE TITLE
Go back after creating anything

### ISSUE THREAD

**Issue by maharifu** [jcazevedo/pawned#19]
After creating anything (round, dual, match, etc.), you should go back to where you were.
Alternatively, one could show what was just created, but have a button to go back.

**Comment by punnie** [comment]
I got no strong opinion on the behavior. The only thing I ask about this is for the flow between pages to be _consistent_ (e.g. the back button on an item always goes back to the collection of those items). It would save us a lot of work as developers and will save a lot of work for the user as soon as he learns what's our pattern. If we agree on one good pattern, we should follow it with the least possible exceptions.

Also, due to the strict hierarchy we have for the tournaments > rounds > duels > matches, I suggest we start thinking about "hierarchical breadcrumbs". They may aid a lot navigating the system.

**Comment by jcazevedo** [comment]
I agree with @punnie.

**Comment by maharifu** [comment]
I also agree. This was here so I don't forget to do it... :p

But still, not all 'Back' buttons are born the same: going from 'All Tournaments' > 'Edit Tournament #1' > Back would take you where?

Maybe it's just me, but I don't like that. I like the idea of breadcrumbs, though. Or we call the button 'Go Up'.

**Comment by jcazevedo** [comment]
IMO, if we have breadcrumbs, there's no need for a back button.

**Comment by punnie** [comment]
Just because the rails scaffolding mechanism put a button named "back" on
the page doesn't mean we have to stick with it. We may call it something
else.

I do feel, however, that a "cancel" type of button is necessary. Let it be
named "back", "cancel" or "eat my shorts". It's irrelevant to me. I just
want something for the user to hold onto when he finds himself in a form
page by mistake and he wants to get out of there making sure nothing he's
accidentally done will be applied.

On Mon, Apr 2, 2012 at 11:54 PM, Joao Azevedo <
reply@reply.github.com

> wrote:
> 
> IMO, if we have breadcrumbs, there's no need for a back button.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jcazevedo/pawned/issues/19#issuecomment-4890723

## 

http://pedrocoelho.pt

**Comment by jcazevedo** [comment]
In forms, yes, everywhere else I think it is unnecessary.

**Comment by punnie** [comment]
Agreed.

**Comment by maharifu** [comment]
I actually don't like that button. Mainly because it's redundant as you already have the browser's back button. I personaly don't use it.

But I know I'm the minority here, so 'eat my shorts' it is. But that button should really go back, and not up.

**Comment by punnie** [comment]
Why? We already have a back button on the browser.

**Comment by maharifu** [comment]
Because if you're on All Tournaments, press Edit #1 and then Cancel, you don't want to be on a different place than where you started!

**Comment by punnie** [comment]
Why would you be in a different place from where you started? By my logic that would go back to "All Tournaments".

**Comment by maharifu** [comment]
Because that's what we have right now on most actions and why this issue is here.

**Comment by maharifu** [comment]
This should be working now, with a back button that really goes back. Anything incoherent or not working as supposed to should be opened as a new bug.
