### ISSUE TITLE
Editing a duel creates new matches

### ISSUE THREAD

**Issue by maharifu** [jcazevedo/pawned#29]
The title says it all. ;)

But if we edit a duel to change its players, what happens to the matches of the previous players? And what if they have been played?

Maybe it shouldn't be possible to edit the players of a duel if any of its matches has already been played.

**Comment by punnie** [comment]
I don't like this. The automagic match creation should be a facility available only when _creating_ a duel.

When editing you should only be able to add or remove them by hand.

Oh, and btw: are the players still specified in the matches instead of in the duel data model? They should be stored in the duel. Is there any case where it would make sense to add a match with different players inside a duel between two players?

**Comment by maharifu** [comment]
I guess not. And yes, we should move them to the Duel model, as there will
be no standalone matches. I'll create a new issue.

On 9 April 2012 22:02, Pedro Coelho <
reply@reply.github.com

**Comment by maharifu** [comment]
This should be solved by now.
